/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BecomeAChefRouteImport } from './routes/become-a-chef'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChefsIndexRouteImport } from './routes/chefs.index'
import { Route as ChefsChefIdRouteImport } from './routes/chefs.$chefId'
import { Route as ChefDashboardRouteImport } from './routes/chef.dashboard'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'
import { Route as BookChefIdRouteImport } from './routes/book.$chefId'

const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAChefRoute = BecomeAChefRouteImport.update({
  id: '/become-a-chef',
  path: '/become-a-chef',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefsIndexRoute = ChefsIndexRouteImport.update({
  id: '/chefs/',
  path: '/chefs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefsChefIdRoute = ChefsChefIdRouteImport.update({
  id: '/chefs/$chefId',
  path: '/chefs/$chefId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefDashboardRoute = ChefDashboardRouteImport.update({
  id: '/chef/dashboard',
  path: '/chef/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => BookingsRoute,
} as any)
const BookChefIdRoute = BookChefIdRouteImport.update({
  id: '/book/$chefId',
  path: '/book/$chefId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-a-chef': typeof BecomeAChefRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/book/$chefId': typeof BookChefIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/chef/dashboard': typeof ChefDashboardRoute
  '/chefs/$chefId': typeof ChefsChefIdRoute
  '/chefs/': typeof ChefsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-a-chef': typeof BecomeAChefRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/book/$chefId': typeof BookChefIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/chef/dashboard': typeof ChefDashboardRoute
  '/chefs/$chefId': typeof ChefsChefIdRoute
  '/chefs': typeof ChefsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-a-chef': typeof BecomeAChefRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/book/$chefId': typeof BookChefIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/chef/dashboard': typeof ChefDashboardRoute
  '/chefs/$chefId': typeof ChefsChefIdRoute
  '/chefs/': typeof ChefsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-a-chef'
    | '/bookings'
    | '/book/$chefId'
    | '/bookings/$bookingId'
    | '/chef/dashboard'
    | '/chefs/$chefId'
    | '/chefs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-a-chef'
    | '/bookings'
    | '/book/$chefId'
    | '/bookings/$bookingId'
    | '/chef/dashboard'
    | '/chefs/$chefId'
    | '/chefs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/become-a-chef'
    | '/bookings'
    | '/book/$chefId'
    | '/bookings/$bookingId'
    | '/chef/dashboard'
    | '/chefs/$chefId'
    | '/chefs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BecomeAChefRoute: typeof BecomeAChefRoute
  BookingsRoute: typeof BookingsRouteWithChildren
  BookChefIdRoute: typeof BookChefIdRoute
  ChefDashboardRoute: typeof ChefDashboardRoute
  ChefsChefIdRoute: typeof ChefsChefIdRoute
  ChefsIndexRoute: typeof ChefsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-chef': {
      id: '/become-a-chef'
      path: '/become-a-chef'
      fullPath: '/become-a-chef'
      preLoaderRoute: typeof BecomeAChefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chefs/': {
      id: '/chefs/'
      path: '/chefs'
      fullPath: '/chefs/'
      preLoaderRoute: typeof ChefsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chefs/$chefId': {
      id: '/chefs/$chefId'
      path: '/chefs/$chefId'
      fullPath: '/chefs/$chefId'
      preLoaderRoute: typeof ChefsChefIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/dashboard': {
      id: '/chef/dashboard'
      path: '/chef/dashboard'
      fullPath: '/chef/dashboard'
      preLoaderRoute: typeof ChefDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/book/$chefId': {
      id: '/book/$chefId'
      path: '/book/$chefId'
      fullPath: '/book/$chefId'
      preLoaderRoute: typeof BookChefIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookingsRouteChildren {
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsBookingIdRoute: BookingsBookingIdRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BecomeAChefRoute: BecomeAChefRoute,
  BookingsRoute: BookingsRouteWithChildren,
  BookChefIdRoute: BookChefIdRoute,
  ChefDashboardRoute: ChefDashboardRoute,
  ChefsChefIdRoute: ChefsChefIdRoute,
  ChefsIndexRoute: ChefsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
